output "vm_id" {
  description = "VM ID Proxmox allocated for the machine."
  value       = module.vm.vm_id
}

output "mac_addresses" {
  description = "MAC of each NIC — generated by Proxmox here, since the example pins none. Useful for a DHCP reservation."
  value       = module.vm.mac_addresses
}

output "ipv4_addresses" {
  description = "Addresses the guest reports through the QEMU guest agent. Empty in this example, which runs with agent_enabled = false."
  value       = module.vm.ipv4_addresses
}
